Update README.md
ethcatherders/EIPIP pull request #203
Opened 2022-12-21 13:22 UTC by Henryjk4

2022-12-21 17:33 UTC, Pandapip1 requested changes

2022-12-21 17:33 UTC, Pandapip1 commented on README.md
> +  71 | Wednesday, Dec 14, 2022, at 15:00 UTC | [Agenda](https://github.com/ethereum-cat-herders/EIPIP/issues/198) | [Notes](https://github.com/Henryjk4/EIPIP/commit/9e8ccbb967430eaf10b65f50a2ac525e08
```suggestion
  71 | Wednesday, Dec 14, 2022, at 15:00 UTC | [Agenda](https://github.com/ethereum-cat-herders/EIPIP/issues/198) | [Notes](All%20EIPIP%20Meetings/Meeting%20071.md) | [Video](https://www.youtube.com/watch?v=ylDXaR31gYg)
```

2022-12-27 23:46 UTC, poojaranjan commented
@Henryjk4 unable to find PR to notes 71. Can you make a PR and then update the README accordingly?

2023-04-05 13:24 UTC, poojaranjan commented
Updated with later PRs.

2023-04-05 13:24 UTC, closed without merging